[project]
name = "python-counter-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["monsterui>=1.0.21", "python-fasthtml>=0.12.19"]
